site_name: Expressive Regex
repo_name: 'fsadannn/expressive_regex'
repo_url: 'https://github.com/fsadannn/expressive_regex'

theme:
    name: material
    feature:
        tabs: true

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition

nav:
    - Home: index.md
    - API:
        - Literals: api/literals.md
        - Quantifiers: api/quantifiers.md
        - Grouping: api/grouping.md
        #- Boundary Matchers: api/boundary_matchers.md
